### ISSUE TITLE
I cannot find the BIN file in LINUX.

### ISSUE THREAD

**Issue by muramura** [ArduPilot/plotjuggler-apbin-plugins#10]
I tried to analyze log files in LINUX using this plugin.
However, the log files could not be found.
PLOTJUGGLER was using lowercase "bin" as the file extension.
WINDOWS treats uppercase and lowercase letters the same.
However, many LINUX distributions distinguish between uppercase and lowercase letters.
I submitted a PR to PLOTJUGGLER. 

https://github.com/facontidavide/PlotJuggler/pull/1003

**Comment by Georacer** [comment]
This is a known drawback of PlotJuggler. I have also left a similar ["feature request"](https://github.com/facontidavide/PlotJuggler/issues/977).

I'm closing this, this is not something we can solve without modifying PlotJuggler itself, as far as I can tell.
